# Generated by Django 3.2.16 on 2023-01-14 18:55

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(help_text='Required. 60 characters or fewer.', max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='last name')),
                ('has_pass', models.BooleanField(default=False, help_text='Shows True if the user has a pass.', verbose_name='Pass')),
                ('pass_is_active', models.BooleanField(default=False, help_text='Shows that the pass is active or not.', verbose_name='Pass_active')),
                ('date_pass_registered', models.DateTimeField(null=True, verbose_name='When the pass regisered with the phone.')),
                ('date_pass_rejected', models.DateTimeField(null=True, verbose_name='when the pass rejected from the user.')),
                ('authentication_device', models.CharField(max_length=128, null=True, verbose_name='device')),
                ('authentication_device_id', models.CharField(max_length=128, null=True, unique=True, verbose_name='device')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
