# Generated by Django 3.2.16 on 2023-05-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandler', '0002_auto_20230507_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
