"""
Django settings for SenityProject project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%*6*^mwwx@&scc2tidi(xc4!-)u6)6#@7sbtacrnv4xa9rfd!k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

STATIC_ROOT = os.path.join(BASE_DIR.parent, 'static')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sitemaps",
    "UserHandler",
    "bootstrap5",
    "django_walletpass",
    'rest_framework',
    "GooglePass",
    "django_user_agents"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'SenityProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'static', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = "UserHandler.Account"
WSGI_APPLICATION = 'SenityProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST=os.environ.get('EMAIL_HOST')
EMAIL_HOST_USER=os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD=os.environ.get('EMAIL_HOST_PASSWORD')
EMIAL_USE_TLS=os.environ.get('EMIAL_USE_TLS')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL')
EMAIL_PORT=os.environ.get('EMAIL_PORT')
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
RECAPTCHA_SITE_KEY=os.environ.get('RECAPTCHA_SITE_KEY')
RECAPTCHA_SECRET_KEY=os.environ.get('RECAPTCHA_SECRET_KEY')
RECAPTCHA_REQUIRED_SCORE = 0.85
APPLE_CER_PEM=os.environ.get("APPLE_CER_PEM")
APPLE_KEY_PEM=os.environ.get("APPLE_KEY_PEM")
APPLE_CERT_PASS=os.environ.get("APPLE_CERT_PASS")
APPLE_CERT_PASS_BYTES = APPLE_CERT_PASS.encode() if APPLE_CERT_PASS else None
APPLE_PASS_TYPE_IDENTIFIER=os.environ.get("APPLE_PASS_TYPE_IDENTIFIER")
APPLE_TEAM_ID=os.environ.get("APPLE_TEAM_ID")
APPLE_WWDR_PEM=os.environ.get("APPLE_WWDR_PEM")
APPLE_LOGO=os.environ.get("APPLE_LOGO")
APPLE_ICON=os.environ.get("APPLE_ICON")
APPLE_ICON_X2=os.environ.get("APPLE_ICON_X2")
APPLE_ICON_X3=os.environ.get("APPLE_ICON_X3")
APPLE_NFC_PUB_KEY=os.environ.get("APPLE_NFC_PUB_KEY")
APPLE_TOKEN_KEY_ID=os.environ.get("APPLE_TOKEN_KEY_ID")
APPLE_TOKEN_AUTH_KEY_FILE=os.environ.get("APPLE_TOKEN_AUTH_KEY_FILE")
APPLE_PASS_JSON_PATH=os.environ.get("APPLE_PASS_JSON_PATH")
GOOGLE_APPLICATION_CREDENTIALS=os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
GOOGLE_ISSUER_ID=os.environ.get("GOOGLE_ISSUER_ID")
GOOGLE_PASS_CLASS=os.environ.get("GOOGLE_PASS_CLASS")

WALLETPASS = {
    'CERT_PATH': APPLE_CER_PEM,
    'KEY_PATH': APPLE_KEY_PEM,
    'KEY_PASSWORD': APPLE_CERT_PASS_BYTES,
    'PASS_TYPE_ID': APPLE_PASS_TYPE_IDENTIFIER,
    'TEAM_ID': APPLE_TEAM_ID,
    'SERVICE_URL': 'https://senitysecuritysystems.com/api/passes/',
    'PUSH_AUTH_STRATEGY': 'token',
    'TOKEN_AUTH_KEY_PATH': APPLE_TOKEN_AUTH_KEY_FILE,
    'TOKEN_AUTH_KEY_ID': APPLE_TOKEN_KEY_ID,
    "APPLE_WWDRCA_PEM_PATH": APPLE_WWDR_PEM,
    'STORAGE_CLASS': 'django.core.files.storage.FileSystemStorage',
    'UPLOAD_TO': 'passes',
    "STORAGE_HTTP_REDIRECT": True,
    'PUSH_SANDBOX': False
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/home/pi/WebService/passwebservice/SenityProject/debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        '__main__': {  # Allows to log from the main module (your views, models, etc.)
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django_walletpass': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'UserHandler': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'GooglePass': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}